import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { GeminiFunction } from "./useContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <GeminiFunction>
              {children}
            </GeminiFunction>
            <Toaster    position="top-right"
            toastOptions={{
              success: {
                style: { background: "#4ade80", color: "#fff" },
              },
              error: {
                style: { background: "#ef4444", color: "#fff" },
              }}}/>
        </body>
      </html>
    </ClerkProvider>
  );
}
